import styles from '../styles/Home.module.css'

function Register() {
  return (
    <div>
      <title>Signup</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <div>
        <h1>This is where you sign up</h1>
      </div>
    </div>
  )
}

export default Register